### PR TITLE
Migrate to Guzzle 6

### LINKED ISSUE #13: Guzzle 6.x compatibility
@owner

The FHPostcodeAPIClient seems not yet compatible with Guzzle ^6.*.

Any plans for updating?

### PR DESCRIPTION
**Pull request by slokhorst**
Use Guzzle version 6 instead of 5.

Also streamline the testing experience by adding `require-dev` and a test script to the composer file.

Fixes #13

### CODE REVIEW

**Comment by slokhorst** [comment]
Note: I've revised the PR and all the issues from the first attempt should be fixed.

**Comment by jvandesande** [comment]
Thanks for your work! 

Unfortunately we cannot merge your PR, because we want to use [HTTP Plug](http://httplug.io/) in the next major version of the API client. So the user of the library can choose which HTTP client implementation is used. 

It would be great if you could update your PR.

**Comment by evertharmeling** [comment]
Thanks @slokhorst I was just working on the HTTPPlug implementation, I've used some of your code ;)

**Comment by slokhorst** [comment]
@evertharmeling Good! I didn't have time to look at HTTPlug myself yet, but it's nice to know that my work wasn't completely useless. :)

**Pull request closed without merging**
